#!/usr/bin/env bash
# configs new ubuntu machice w ngix

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo 'Holberton School' > sudo tee /usr/share/ngnix/html/index.html
sudo service nqinx start
