#!/usr/bin/env bash
# Installs and configures Ngix server with custom redirect

FILE=/etc/nginx/sites-available/default
REDIRECT="location /redirect_me {\n return 301  https://www.youtube.com/watch?v=N_aqYAi2sWA;\n}\n"

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html

sudo sed -i "30i $REDIRECT" $FILE

sudo service nginx start
