#!/bin/bash
cd 3-listfiles 4-listmorefiles 5-listfilesdigitonly 6-firstdirectory 7-movethatfile 8-firstdelete 9-firstdirdeletion 10-back 11-lists 12-file_type 13-symbolic_link 14-copy_html 15-lets_move 16-clean_emacs 17-tree 18-commas holberton.mgc
