#!/usr/bin/env bash
# creates a file then deletes upon sig signal
echo "$!> /var/run/holbertonscript.pid"
counter=1
while [ $counter ]
do
	echo "To infinty and beyond"
	sleep 2
	trap "I hate the kill command" 15; rm -f /var/run/holbertonscript.pid
	trap "Y u no love me?!" 2
done	
