#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

name='Holberton Holberton Holberton Holberton Holberton Holberton Holberton Holberton Holberton Holberton'

for names in $name
do
	echo "$names"
done
