#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
counter=1
while [ $counter -lt 10 ]
do
	echo "Holberton School"
	((counter++))
	if [ $counter -eq 9 ]
	then
		echo "Hi"
		continue
	fi
done
