#!/usr/bin/env bash
# Display "Holberton School" 10 times, differnt on 4th,8th, iteration
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((counter++))
done

