#!/usr/bin/env bash
# show 1-20, different 4,9,17
counter=1
while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in
	4)
		echo "bad luck from china";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
	esac
	((counter++))
done
