#!/usr/bin/env bash
# gives info about a file
file="holbertonschool"
if [ -e "$filename" ]
then
	echo "$file exists"
	if [ -s $file ]
	then
		echo "$file is not empty"
	else
		echo "$file does note exist"
	fi
	if [ -f $file ]
	then
		echo "$file is a regular file"
	fi
else
	echo "$file does not exist"
fi

