#!/usr/bin/env bash
# configure nginx user
sudo chmod 744 /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
